# Generated by Django 5.1.7 on 2025-04-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_old_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="structure",
            field=models.TextField(blank=True, verbose_name="Состав"),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Kilogram", "кг"),
                    ("Gram", "гр"),
                    ("Liter", "л"),
                    ("Piece", "шт"),
                    ("Package", "уп"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
